@startuml Future_conda_strategy
left to right direction
node repo [
    Mantid Source Code
]
cloud AnacondaCloud {
    node MantidFramework
    node MantidQt
    node MantidWorkbench
    node MantidIndirect
    node MantidMuon
    node MantidDirect
    node MantidLSS
    node MantidMSlice
    node MantidCore
}   

artifact MantidWorkbenchFull
artifact MantidWorkbenchIndirect
artifact MantidWorkbenchDirect
artifact MantidWorkbenchLSS
artifact MantidWorkbenchMuon
artifact MantidWorkbenchMinimal

repo --> MantidFramework
repo --> MantidQt
repo --> MantidWorkbench
repo --> MantidIndirect
repo --> MantidMuon
repo --> MantidDirect
repo --> MantidLSS
repo --> MantidMSlice
repo --> MantidCore

MantidFramework --> Scipp
MantidFramework --> Autoreduction
MantidFramework --> MantidIndirect
MantidFramework --> MantidDirect
MantidFramework --> MantidMuon
MantidFramework --> MantidLSS
MantidFramework --> MantidMSlice
MantidFramework --> MantidCore

MantidQt --> MantidWorkbench
MantidQt --> MantidIndirect
MantidQt --> MantidDirect
MantidQt --> MantidMuon
MantidQt --> MantidLSS
MantidQt --> MantidMSlice
MantidQt --> MantidCore

MantidWorkbench --> MantidWorkbenchFull
MantidWorkbench --> MantidWorkbenchIndirect
MantidWorkbench --> MantidWorkbenchDirect
MantidWorkbench --> MantidWorkbenchLSS
MantidWorkbench --> MantidWorkbenchMinimal
MantidWorkbench --> MantidWorkbenchMuon

MantidIndirect --> MantidWorkbenchFull
MantidIndirect --> MantidWorkbenchIndirect

MantidDirect --> MantidWorkbenchFull
MantidDirect --> MantidWorkbenchDirect

MantidMSlice --> MantidWorkbenchFull
MantidMSlice --> MantidWorkbenchDirect

MantidLSS --> MantidWorkbenchFull
MantidLSS --> MantidWorkbenchLSS

MantidCore --> MantidWorkbenchFull
MantidCore --> MantidWorkbenchIndirect
MantidCore --> MantidWorkbenchDirect
MantidCore --> MantidWorkbenchLSS
MantidCore --> MantidWorkbenchMuon
MantidCore --> MantidWorkbenchMinimal


@enduml