######################################################################
#Python Script Generated by Algorithm History Display 
######################################################################
alg=LoadNexusDialog(OutputWorkspace='trans')
filename=alg.getPropertyValue("FileName")
mtd.sendLogMessage("filename was " + filename)
ConvertUnits(InputWorkspace='trans',OutputWorkspace='trans',Target='Wavelength')
RebinDialog(InputWorkspace='trans',OutputWorkspace='trans',Params='?2.5,0.1,5.5',PreserveEvents=True)
SumSpectra(InputWorkspace='trans',OutputWorkspace='beam_profile')
